### ISSUE TITLE
Should be marked deprecated

### ISSUE THREAD

**Issue by zoellner** [evgenykireev/serverless-api-compession#1]
Serverless supports this out of the box by now. 
This repo while it served its purpose should probably be marked deprecated now to not mislead people coming here from search results.

**Comment by Sigmus** [comment]
Does it? How?

**Comment by zoellner** [comment]
set the minimum compression size it in the provider config
```
provider:
  name: aws
  apiGateway:
    minimumCompressionSize: 1024
```
